name = "gavdaly"
compatibility_date = "2024-12-01"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "gavdaly-index"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "gavdaly-images"
